### ISSUE TITLE
Why do we include runner.html for testing?

### ISSUE THREAD

**Issue by cognitom** [riot/observable#4]
I'm not sure the reason..., just curious.
Sometimes useful for debugging the tests, but keeping the test simple seems more important for me.
@GianlucaGuarini how about?

**Comment by GianlucaGuarini** [comment]
What do you mean? There is no file called karma.html.. Do you mean runner.html?

**Comment by cognitom** [comment]
Yes. Sorry my typo.

**Comment by GianlucaGuarini** [comment]
Sometimes I need to run the tests on several devices, using browserstack for example, and having a simple html file is the easiest solution to check whether everything works fine or not. 
For example in `riot-route` you may need to check all your tests on a real android device (due to the poor html5 history api support) because you can't rely 100% on karma for this kind of tests.

**Comment by cognitom** [comment]
Definitely. Thanks!

Syncing `karma.conf.js` and `runner.html` is a little annoying... I'll look for some way.
